In [14]:
import pandas as pd
#import pyarrow as pa
import numpy as np
import sympy as sy

from evaluation import FileAnswer, Quizz
file_answer = FileAnswer('CURSO', 'Tema1', 'local')
quizz = Quizz('1', 'CURSO', 'Tema1', 'local')

In [3]:
t = np.linspace(0,1,10)
t

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [4]:
file_answer.write('1a', t, 'Deberías checar ...')

In [5]:
w = np.sin(t)
w

array([0.        , 0.11088263, 0.22039774, 0.3271947 , 0.42995636,
       0.52741539, 0.6183698 , 0.70169788, 0.77637192, 0.84147098])

In [6]:
file_answer.write('1b', w)

Escoge una opción entre: A, B, C, D, E

In [7]:
file_answer.write('2', 'c', 'Las opciones válidas son ...')

¿Cuál es la derivada de $f(x) = \frac{x^3}{3}$?

In [8]:
file_answer.write('3', 'x**2', 'Checa las reglas de derivación')

Sistema de ecuaciones lineales:

$$
\left[
\begin{array}{cc}
0.10 & -1 \\
0.35 & -1
\end{array} \right]
\left[
\begin{array}{c}
x \\
y
\end{array} \right] =
\left[
\begin{array}{c}
-200 \\ 
-20
\end{array} \right] \tag{2}
$$

In [9]:
A = np.array([[0.10, -1.],[0.30,-1.]] )
B = np.array([-200, 20])
C = 0

In [10]:
file_answer.write('4', A, 'Checa las entradas de la matriz A')
file_answer.write('5', B, 'Checa las entradas del vector B')
file_answer.write('6', C, 'Checa el valor de C')

### Forma cuadrática

$$ f(\mathbf{x}) = \dfrac{1}{2} \mathbf{x}^T A \mathbf{x} - \mathbf{b}^T \mathbf{x} + c $$

Usando los valores de $A$, $B$ y $C$ calcula la forma de $f(\mathbf{x})$

In [11]:
file_answer.write('7', '0.05*x**2 - 0.35*x*y + 200*x - 0.5*y**2 - 20 * y', 'Revisa tus operaciones algebráicas para calcular f(x)')

In [12]:
file_answer.to_file('1')

El directorio :/home/luiggi/GitSites/macti_lib/macti/CURSO/utils/.ans/Tema1/ ya existe
Respuestas y retroalimentación almacenadas.

In [15]:
ans_df2 = pd.read_parquet('../utils/.ans/Tema1/.__ans_1') # Se lee en un DataFrame
ans_df2

,1a,1b,2,3,4,5,6,7
0,"[0.0, 0.1111111111111111, 0.2222222222222222, ...","[0.0, 0.11088262850995298, 0.22039774345612226...",c,x**2,"[0.1, -1.0, 0.3, -1.0]","[-200, 20]",0,0.05*x**2 - 0.35*x*y + 200*x - 0.5*y**2 - 20 * y

In [16]:
fee_df2 = pd.read_parquet('../utils/.ans/Tema1/.__fee_1') # Se lee en un DataFrame
fee_df2

,1a,1b,2,3,4,5,6,7
0,Deberías checar ...,None,Las opciones válidas son ...,Checa las reglas de derivación,Checa las entradas de la matriz A,Checa las entradas del vector B,Checa el valor de C,Revisa tus operaciones algebráicas para calcul...

# Evaluación de las respuestas

In [17]:
quizz.eval_numeric('1a', t)

--------------------------------------------------------------------------------
Tu resultado es correcto.
--------------------------------------------------------------------------------

In [18]:
quizz.eval_numeric('1b', w)

--------------------------------------------------------------------------------
Tu resultado es correcto.
--------------------------------------------------------------------------------

In [19]:
quizz.eval_option('2', 'c')

--------------------------------------------------------------------------------
Tu respuesta: c, es correcta.
--------------------------------------------------------------------------------

In [20]:
x = sy.Symbol('x')
resultado = x*x
display(resultado)

x**2

In [21]:
quizz.eval_expression('3', resultado)

--------------------------------------------------------------------------------
Tu respuesta:

x**2

es correcta.
--------------------------------------------------------------------------------

In [22]:
quizz.eval_numeric('4', A)

--------------------------------------------------------------------------------
Tu resultado es correcto.
--------------------------------------------------------------------------------

In [23]:
quizz.eval_numeric('5', B)

--------------------------------------------------------------------------------
Tu resultado es correcto.
--------------------------------------------------------------------------------

In [24]:
quizz.eval_numeric('6', C)

--------------------------------------------------------------------------------
Tu resultado es correcto.
--------------------------------------------------------------------------------

In [25]:
x = sy.Symbol('x')
y = sy.Symbol('y')

In [26]:
respuesta = 0.5 * A[0,0] * x**2 + 0.5 * A[1,1] * y**2 + 0.5 * (A[0,1]+A[1,0])* x * y - B[0] * x - B[1] * y + C

In [27]:
quizz.eval_expression('7', respuesta)

--------------------------------------------------------------------------------
Tu respuesta:

0.05*x**2 - 0.35*x*y + 200*x - 0.5*y**2 - 20*y

es correcta.
--------------------------------------------------------------------------------