In [1]:
import pandas as pd
import pyarrow as pa
import numpy as np
import sympy as sy

from evaluation import FileAnswer, Quizz
file_answer = FileAnswer('CURSO', 'Tema1', 'local')
quizz = Quizz('CURSO', 'Tema1', 'local')

In [2]:
x = np.linspace(0,1,10)
x

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [3]:
y = np.sin(x)
y

array([0.        , 0.11088263, 0.22039774, 0.3271947 , 0.42995636,
       0.52741539, 0.6183698 , 0.70169788, 0.77637192, 0.84147098])

In [4]:
file_answer.write('1', y, 'Deberías checar ...')

In [5]:
file_answer.write('2a', y)

In [6]:
file_answer.write('2b', ['C', 'c'], 'las opciones son las siguientes ...')

In [7]:
file_answer.write('3', 'x**2', 'Checa las reglas de derivación')

In [8]:
file_answer.to_file('1')

C:\Users\luiggi\Documents\GitSites\macti_lib\macti\CURSO\utils\.ans\Tema1\.__ans_1
C:\Users\luiggi\Documents\GitSites\macti_lib\macti\CURSO\utils\.ans\Tema1\.__fee_1

In [9]:
ans_df2 = pd.read_parquet('../utils/.ans/Tema1/.__ans_1') # Se lee en un DataFrame
ans_df2

,1,2a,2b,3
0,"[0.0, 0.11088262850995298, 0.22039774345612226...","[0.0, 0.11088262850995298, 0.22039774345612226...","[C, c]",x**2

In [10]:
fee_df2 = pd.read_parquet('../utils/.ans/Tema1/.__fee_1') # Se lee en un DataFrame
fee_df2

,1,2a,2b,3
0,Deberías checar ...,None,las opciones son las siguientes ...,Checa las reglas de derivación

In [11]:
quizz.eval_numeric('1', '1', x)

--------------------------------------------------------------------------------
Ocurrió un error en tus cálculos.
--------------------------------------------------------------------------------
Hint: Deberías checar ...
--------------------------------------------------------------------------------

AssertionError:

In [ ]:
quizz.eval_numeric('1', '2a', y)

In [ ]:
quizz.eval_option('1', '2b', 'C')

In [ ]:
x = sy.Symbol('x')
resultado = x*x*3
display(resultado)

In [ ]:
quizz.eval_expression('1', '3', resultado)