In [69]:
import pandas as pd
import pyarrow as pa
import numpy as np
from evaluation import FileAnswer

In [70]:
l1 = ['1','2','2a','4']
l2 = [1,2,3,4]
l3 = np.array(['a', 'b', 'c', 'd'])

In [72]:
ans_df = pd.DataFrame([l2], columns=l1)
feed_df = pd.DataFrame([l3], columns=l1)

In [75]:
ans_df

   1  2  2a  4
0  1  2   3  4

In [74]:
feed_df

   1  2 2a  4
0  a  b  c  d

In [76]:
ans_df.to_parquet('ans.parquet', compression='gzip')
feed_df.to_parquet('feed.parquet', compression='gzip')

In [78]:
ansr = pd.read_parquet('ans.parquet', columns=['2a']) # Se lee en un DataFrame
feedr = pd.read_parquet('feed.parquet', columns=['2a']) # Se lee en un DataFrame

In [79]:
ansr

   2a
0   3

In [80]:
feedr

  2a
0  c